export const Size = {
  MOBILE_WIDTH: 480, // px
  MOBILE_HORIZONTAL_MIN_WIDTH: 320, // px
  TABLET_WIDTH: 768, // px
  DESKTOP_WIDTH: 1200, // px
  MAIN_PICTURE_HEIGHT: '42.39474vw',
  MAIN_PICTURE_HEIGHT_MOBILE: '222.8125vw',
  FIRST_SCREEN_MARGIN_TOP: 157, // px
  FIRST_SCREEN_MARGIN_TOP_MOBILE: 95, // px
  MAIN_PAGE_OFFSET: 6, // px
}
